"""export_to_coreml.py — convert a .tinygpt checkpoint to a Core ML mlpackage
that runs on the Apple Neural Engine.

The path is:
    .tinygpt  →  PyTorch state_dict  →  traced TinyGPT module  →  .mlpackage

The .mlpackage runs from Swift via MLModel with computeUnits=.cpuAndNeuralEngine,
which dispatches eligible ops to the ANE (16-core, ~38 TOPS on M3+).

Expected speedup on sampling: 3-10x vs MLX-Swift's Metal path for the same
checkpoint. Training stays on MLX-Swift; ANE is forward-only.

USAGE
=====

    pip install torch coremltools numpy
    python3 python_ref/export_to_coreml.py \\
        --in path/to/model.tinygpt \\
        --out path/to/model.mlpackage \\
        --max-context 256

The converted package is bundled by the Swift side (Sources/TinyGPTApp/Resources/)
and loaded by TinyGPTANE.swift. See native-mac/Sources/TinyGPTANE/ once the
Swift integration lands.

KNOWN HAZARDS
=============

1. Not every transformer op is ANE-friendly. Sequoia+ added matmul/softmax/
   layernorm support, but specific shapes may silently fall back to CPU.
   Diagnose with `python -c "import coremltools as ct; ct.utils.evaluate_with_runtime(...)"`
   or by profiling the model in Xcode (Instruments → Core ML).

2. WASM weight layout (the bug TinyGPTWeightLoader handles). load_tinygpt.py
   currently does NOT transpose; this script MUST transpose Linear weights
   to PyTorch's [out, in] order before constructing nn.Linear. See
   `_remap_wasm_weights` below.

3. The checkpoint is fp16 in the gallery files but fp32 in browser exports.
   We dequantise everything to fp32 for the PyTorch model; coremltools then
   re-quantises to fp16 for ANE on conversion.

4. ANE peaks on KV-cached single-token forward (the sampling shape). The
   converted model takes a fixed-length prompt; for true sampling speedup,
   you want to also export a separate "one-token-with-cache" variant. That
   second model isn't generated by this script yet.
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path

try:
    import numpy as np
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
except ImportError as e:
    print(f"missing dependency: {e}", file=sys.stderr)
    print("install with:  pip install torch numpy coremltools", file=sys.stderr)
    sys.exit(1)

try:
    import coremltools as ct
except ImportError:
    print("missing coremltools — install with: pip install coremltools", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Model — minimal forward-only port of python_ref/model.py without the
# train-time machinery (dropout, weight init). The names match so the
# state_dict loads.
# ---------------------------------------------------------------------------


class CausalSelfAttention(nn.Module):
    def __init__(self, d_model: int, n_heads: int, ctx: int):
        super().__init__()
        self.n_heads = n_heads
        self.head_dim = d_model // n_heads
        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(d_model, d_model)
        self.v_proj = nn.Linear(d_model, d_model)
        self.o_proj = nn.Linear(d_model, d_model)
        # Pre-baked causal mask. We register it as a buffer so it ships with
        # the traced model.
        mask = torch.tril(torch.ones(ctx, ctx))
        self.register_buffer("causal_mask", mask.view(1, 1, ctx, ctx))

    def forward(self, x):
        B, T, C = x.shape
        q = self.q_proj(x).view(B, T, self.n_heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(B, T, self.n_heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(B, T, self.n_heads, self.head_dim).transpose(1, 2)
        scores = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        scores = scores.masked_fill(self.causal_mask[:, :, :T, :T] == 0, float("-inf"))
        attn = F.softmax(scores, dim=-1)
        out = (attn @ v).transpose(1, 2).contiguous().view(B, T, C)
        return self.o_proj(out)


class MLP(nn.Module):
    def __init__(self, d_model: int, d_mlp: int):
        super().__init__()
        self.fc_in = nn.Linear(d_model, d_mlp)
        self.fc_out = nn.Linear(d_mlp, d_model)

    def forward(self, x):
        return self.fc_out(F.gelu(self.fc_in(x)))


class Block(nn.Module):
    def __init__(self, d_model: int, n_heads: int, d_mlp: int, ctx: int):
        super().__init__()
        self.ln1 = nn.LayerNorm(d_model)
        self.attn = CausalSelfAttention(d_model, n_heads, ctx)
        self.ln2 = nn.LayerNorm(d_model)
        self.mlp = MLP(d_model, d_mlp)

    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x


class TinyGPT(nn.Module):
    def __init__(self, vocab: int, ctx: int, n_layers: int, n_heads: int, d_model: int, d_mlp: int):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab, d_model)
        self.position_embedding = nn.Embedding(ctx, d_model)
        self.blocks = nn.ModuleList(
            Block(d_model, n_heads, d_mlp, ctx) for _ in range(n_layers)
        )
        self.ln_final = nn.LayerNorm(d_model)
        # Tied output head — reuses token_embedding.weight.

    def forward(self, idx):
        B, T = idx.shape
        pos = torch.arange(T, device=idx.device)
        x = self.token_embedding(idx) + self.position_embedding(pos)
        for block in self.blocks:
            x = block(x)
        x = self.ln_final(x)
        logits = F.linear(x, self.token_embedding.weight)
        return logits


# ---------------------------------------------------------------------------
# .tinygpt loader (mirrors the Swift TinyGPTWeightLoader logic, including
# the WASM-shape transpose for Linear weights).
# ---------------------------------------------------------------------------


def _is_linear_weight(name: str) -> bool:
    if not name.endswith(".weight"):
        return False
    if name in ("token_embedding.weight", "position_embedding.weight"):
        return False
    if name.endswith(".ln1.weight") or name.endswith(".ln2.weight") or name == "ln_final.weight":
        return False
    return True


def load_tinygpt(path: Path) -> tuple[dict, dict[str, np.ndarray]]:
    with open(path, "rb") as f:
        prefix = f.read(12)
        magic, version, header_len = struct.unpack("<4sII", prefix)
        if magic != b"TGPT":
            raise ValueError(f"bad magic {magic!r}")
        header = json.loads(f.read(header_len))
        config = header["config"]
        manifest = header["manifest"]
        weight_dtype = header.get("weightDtype", "fp32")
        includes_optim = header.get("includesOptimizerState", True)
        f.read(4)  # step
        body = f.read()

    # The WASM C++ stores Linear weights as [in, out] (so y = x @ W directly).
    # The browser dumps raw memory; the manifest claims PyTorch's [out, in]
    # but the BYTES are in WASM's [in, out] order. To recover the PyTorch
    # view we must read with WASM shape (the manifest's reversed dims) then
    # transpose. This mirrors what TinyGPTWeightLoader.swift does on the
    # Swift side. For 1D weights and Embedding, no transpose needed.
    def _shape_for_read(entry):
        shape = entry["shape"]
        if _is_linear_weight(entry["name"]) and len(shape) == 2:
            return shape[::-1]  # [in, out] — WASM's actual byte order
        return shape

    def _maybe_transpose(name, arr):
        if _is_linear_weight(name) and arr.ndim == 2:
            return arr.T.copy()
        return arr

    state = {}
    if weight_dtype == "fp16" or not includes_optim:
        # Contiguous fp16 body, indexed by floatOffset.
        flat = np.frombuffer(body, dtype=np.float16).astype(np.float32)
        for entry in manifest:
            n = int(np.prod(entry["shape"]))
            off = entry.get("floatOffset", 0)
            arr = flat[off : off + n].reshape(_shape_for_read(entry)).copy()
            state[entry["name"]] = _maybe_transpose(entry["name"], arr)
    else:
        # fp32 [w, m, v] triplets per tensor.
        flat = np.frombuffer(body, dtype=np.float32)
        offset = 0
        for entry in manifest:
            n = int(np.prod(entry["shape"]))
            arr = flat[offset : offset + n].reshape(_shape_for_read(entry)).copy()
            state[entry["name"]] = _maybe_transpose(entry["name"], arr)
            offset += 3 * n  # skip past m, v
    return config, state


# ---------------------------------------------------------------------------
# Conversion
# ---------------------------------------------------------------------------


def build_torch_model(config: dict, state: dict[str, np.ndarray]) -> TinyGPT:
    model = TinyGPT(
        vocab=256,
        ctx=config["ctx"],
        n_layers=config["layers"],
        n_heads=config["heads"],
        d_model=config["dModel"],
        d_mlp=config["dMlp"],
    )
    sd = {k: torch.from_numpy(v) for k, v in state.items()}
    # The model has no `lm_head` (tied embeddings), and the state dict has
    # no `causal_mask` (registered as a buffer). Allow both.
    missing, unexpected = model.load_state_dict(sd, strict=False)
    if unexpected:
        print(f"warning: unexpected state keys: {unexpected[:5]} (showing first 5)", file=sys.stderr)
    if missing:
        # Filter out causal_mask (built at construction time).
        miss = [k for k in missing if not k.endswith("causal_mask")]
        if miss:
            print(f"warning: missing state keys: {miss[:5]}", file=sys.stderr)
    model.eval()
    return model


def convert_to_coreml(model: TinyGPT, ctx: int, out_path: Path) -> None:
    # Trace at a representative prompt length. For variable-length we'd
    # need MLProgram with `RangeDim`, but fixed-shape is more ANE-friendly.
    example = torch.randint(0, 256, (1, ctx), dtype=torch.int32)
    with torch.no_grad():
        traced = torch.jit.trace(model, example)

    # Convert. computeUnits=ALL lets Core ML route per-op to ANE/GPU/CPU.
    # compute_precision=FLOAT32 preserves numerics (an aggressive fp16 cast
    # destroyed sample quality in our first attempt). Core ML can still
    # internally quantise ANE-eligible ops if it wants; we just declare
    # the upper bound.
    mlmodel = ct.convert(
        traced,
        inputs=[ct.TensorType(name="tokens", shape=(1, ctx), dtype=np.int32)],
        outputs=[ct.TensorType(name="logits", dtype=np.float32)],
        compute_units=ct.ComputeUnit.ALL,
        compute_precision=ct.precision.FLOAT32,
        minimum_deployment_target=ct.target.macOS14,
        convert_to="mlprogram",
    )
    mlmodel.short_description = "TinyGPT byte-level transformer (ANE-routed)"
    mlmodel.save(str(out_path))
    print(f"✓ wrote {out_path}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--in", dest="inp", required=True)
    p.add_argument("--out", dest="out", required=True)
    p.add_argument("--max-context", type=int, default=None,
                   help="optional override; lower context = faster ANE export + run")
    args = p.parse_args()

    config, state = load_tinygpt(Path(args.inp))
    if args.max_context is not None and args.max_context < config["ctx"]:
        # Crop position_embedding + causal_mask to the requested context.
        config = {**config, "ctx": args.max_context}
        state["position_embedding.weight"] = state["position_embedding.weight"][: args.max_context]

    print(f"config: layers={config['layers']} d_model={config['dModel']} "
          f"ctx={config['ctx']} heads={config['heads']} dMlp={config['dMlp']}")
    model = build_torch_model(config, state)
    print(f"params: {sum(p.numel() for p in model.parameters()):,}")
    convert_to_coreml(model, ctx=config["ctx"], out_path=Path(args.out))


if __name__ == "__main__":
    main()
